export default {
  cart: [],
  anime: [
    {
      anilist_id: 21,
      mal_id: 21,
      format: 0,
      status: 1,
      titles: {
        en: "One Piece",
        jp: "ワンピース",
        it: "One Piece",
      },
      descriptions: {
        en: "",
        it: "Monkey D. Luffy (Nel doppiaggio italiano, Rubber) è un pirata diciassettenne che da bambino ha mangiato il frutto del diavolo Gom Gom che gli ha permesso di diventare un uomo gomma perdendo però la facoltà di nuotare. Il suo sogno è quello di diventare il Re dei pirati trovando il leggendario One Piece, tesoro nascosto da Gol D. Roger, il vecchio Re dei pirati. Per riuscire nell'impresa Rufy dovrà formare la sua ciurma formata da amici e abili combattenti del quali il pirata potrà fidarsi ciecamente. Nasce così la Ciurma di Cappello di Paglia, legata dall'indissolubile legame dell'amicizia.",
      },
      start_date: "1999-10-20T00:00:00Z",
      end_date: "1970-01-01T00:00:00Z",
      season_period: 3,
      season_year: 1999,
      episodes_count: 1001,
      episode_duration: 24,
      cover_image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/nx21-tXMN3Y20PIL9.jpg",
      cover_color: "#e4a15d",
      banner_image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21-wf37VakJmZqs.jpg",
      genres: [
        "Action",
        "Adventure",
        "Comedy",
        "Drama",
        "Fantasy",
        "Pirates",
        "Ensemble Cast",
        "Shounen",
        "Super Power",
        "Conspiracy",
        "Male Protagonist",
        "Ships",
        "Badminton",
        "Airsoft",
        "Time Skip",
        "War",
        "Politics",
        "Lost Civilization",
        "Swordplay",
        "Henshin",
        "Real Robot",
        "Shapeshifting",
        "Animals",
        "Primarily Adult Cast",
        "Cult",
        "Super Robot",
        "Anachronism",
        "Skeleton",
        "Gender Bending",
        "Anti-Hero",
        "Espionage",
        "Ninja",
        "Cyborg",
        "Primarily Male Cast",
        "Guns",
        "Female Harem",
        "Kuudere",
        "Drugs",
        "Robots",
        "Mermaid",
        "Body Swapping",
        "Battle Royale",
        "Zombie",
        "Time Manipulation",
        "Dinosaurs",
        "Transgender",
        "Assassins",
        "Tanned Skin",
        "Adoption",
        "Asexual",
      ],
      score: 86,
      id: 11,
    },
    {
      anilist_id: 21,
      mal_id: 21,
      format: 0,
      status: 1,
      titles: {
        en: "One Piece",
        jp: "ワンピース",
        it: "One Piece",
      },
      descriptions: {
        en: "",
        it: "Monkey D. Luffy (Nel doppiaggio italiano, Rubber) è un pirata diciassettenne che da bambino ha mangiato il frutto del diavolo Gom Gom che gli ha permesso di diventare un uomo gomma perdendo però la facoltà di nuotare. Il suo sogno è quello di diventare il Re dei pirati trovando il leggendario One Piece, tesoro nascosto da Gol D. Roger, il vecchio Re dei pirati. Per riuscire nell'impresa Rufy dovrà formare la sua ciurma formata da amici e abili combattenti del quali il pirata potrà fidarsi ciecamente. Nasce così la Ciurma di Cappello di Paglia, legata dall'indissolubile legame dell'amicizia.",
      },
      start_date: "1999-10-20T00:00:00Z",
      end_date: "1970-01-01T00:00:00Z",
      season_period: 3,
      season_year: 1999,
      episodes_count: 1001,
      episode_duration: 24,
      cover_image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/nx21-tXMN3Y20PIL9.jpg",
      cover_color: "#e4a15d",
      banner_image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21-wf37VakJmZqs.jpg",
      genres: [
        "Action",
        "Adventure",
        "Comedy",
        "Drama",
        "Fantasy",
        "Pirates",
        "Ensemble Cast",
        "Shounen",
        "Super Power",
        "Conspiracy",
        "Male Protagonist",
        "Ships",
        "Badminton",
        "Airsoft",
        "Time Skip",
        "War",
        "Politics",
        "Lost Civilization",
        "Swordplay",
        "Henshin",
        "Real Robot",
        "Shapeshifting",
        "Animals",
        "Primarily Adult Cast",
        "Cult",
        "Super Robot",
        "Anachronism",
        "Skeleton",
        "Gender Bending",
        "Anti-Hero",
        "Espionage",
        "Ninja",
        "Cyborg",
        "Primarily Male Cast",
        "Guns",
        "Female Harem",
        "Kuudere",
        "Drugs",
        "Robots",
        "Mermaid",
        "Body Swapping",
        "Battle Royale",
        "Zombie",
        "Time Manipulation",
        "Dinosaurs",
        "Transgender",
        "Assassins",
        "Tanned Skin",
        "Adoption",
        "Asexual",
      ],
      score: 86,
      id: 11,
    },
    {
      anilist_id: 21,
      mal_id: 21,
      format: 0,
      status: 1,
      titles: {
        en: "One Piece",
        jp: "ワンピース",
        it: "One Piece",
      },
      descriptions: {
        en: "",
        it: "Monkey D. Luffy (Nel doppiaggio italiano, Rubber) è un pirata diciassettenne che da bambino ha mangiato il frutto del diavolo Gom Gom che gli ha permesso di diventare un uomo gomma perdendo però la facoltà di nuotare. Il suo sogno è quello di diventare il Re dei pirati trovando il leggendario One Piece, tesoro nascosto da Gol D. Roger, il vecchio Re dei pirati. Per riuscire nell'impresa Rufy dovrà formare la sua ciurma formata da amici e abili combattenti del quali il pirata potrà fidarsi ciecamente. Nasce così la Ciurma di Cappello di Paglia, legata dall'indissolubile legame dell'amicizia.",
      },
      start_date: "1999-10-20T00:00:00Z",
      end_date: "1970-01-01T00:00:00Z",
      season_period: 3,
      season_year: 1999,
      episodes_count: 1001,
      episode_duration: 24,
      cover_image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/nx21-tXMN3Y20PIL9.jpg",
      cover_color: "#e4a15d",
      banner_image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21-wf37VakJmZqs.jpg",
      genres: [
        "Action",
        "Adventure",
        "Comedy",
        "Drama",
        "Fantasy",
        "Pirates",
        "Ensemble Cast",
        "Shounen",
        "Super Power",
        "Conspiracy",
        "Male Protagonist",
        "Ships",
        "Badminton",
        "Airsoft",
        "Time Skip",
        "War",
        "Politics",
        "Lost Civilization",
        "Swordplay",
        "Henshin",
        "Real Robot",
        "Shapeshifting",
        "Animals",
        "Primarily Adult Cast",
        "Cult",
        "Super Robot",
        "Anachronism",
        "Skeleton",
        "Gender Bending",
        "Anti-Hero",
        "Espionage",
        "Ninja",
        "Cyborg",
        "Primarily Male Cast",
        "Guns",
        "Female Harem",
        "Kuudere",
        "Drugs",
        "Robots",
        "Mermaid",
        "Body Swapping",
        "Battle Royale",
        "Zombie",
        "Time Manipulation",
        "Dinosaurs",
        "Transgender",
        "Assassins",
        "Tanned Skin",
        "Adoption",
        "Asexual",
      ],
      score: 86,
      id: 11,
    },
    {
      anilist_id: 21,
      mal_id: 21,
      format: 0,
      status: 1,
      titles: {
        en: "One Piece",
        jp: "ワンピース",
        it: "One Piece",
      },
      descriptions: {
        en: "",
        it: "Monkey D. Luffy (Nel doppiaggio italiano, Rubber) è un pirata diciassettenne che da bambino ha mangiato il frutto del diavolo Gom Gom che gli ha permesso di diventare un uomo gomma perdendo però la facoltà di nuotare. Il suo sogno è quello di diventare il Re dei pirati trovando il leggendario One Piece, tesoro nascosto da Gol D. Roger, il vecchio Re dei pirati. Per riuscire nell'impresa Rufy dovrà formare la sua ciurma formata da amici e abili combattenti del quali il pirata potrà fidarsi ciecamente. Nasce così la Ciurma di Cappello di Paglia, legata dall'indissolubile legame dell'amicizia.",
      },
      start_date: "1999-10-20T00:00:00Z",
      end_date: "1970-01-01T00:00:00Z",
      season_period: 3,
      season_year: 1999,
      episodes_count: 1001,
      episode_duration: 24,
      cover_image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/nx21-tXMN3Y20PIL9.jpg",
      cover_color: "#e4a15d",
      banner_image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21-wf37VakJmZqs.jpg",
      genres: [
        "Action",
        "Adventure",
        "Comedy",
        "Drama",
        "Fantasy",
        "Pirates",
        "Ensemble Cast",
        "Shounen",
        "Super Power",
        "Conspiracy",
        "Male Protagonist",
        "Ships",
        "Badminton",
        "Airsoft",
        "Time Skip",
        "War",
        "Politics",
        "Lost Civilization",
        "Swordplay",
        "Henshin",
        "Real Robot",
        "Shapeshifting",
        "Animals",
        "Primarily Adult Cast",
        "Cult",
        "Super Robot",
        "Anachronism",
        "Skeleton",
        "Gender Bending",
        "Anti-Hero",
        "Espionage",
        "Ninja",
        "Cyborg",
        "Primarily Male Cast",
        "Guns",
        "Female Harem",
        "Kuudere",
        "Drugs",
        "Robots",
        "Mermaid",
        "Body Swapping",
        "Battle Royale",
        "Zombie",
        "Time Manipulation",
        "Dinosaurs",
        "Transgender",
        "Assassins",
        "Tanned Skin",
        "Adoption",
        "Asexual",
      ],
      score: 86,
      id: 11,
    },
  ],
  sources: [
    {
      genres: [
        "Action",
        "Adventure",
        "Comedy",
        "Drama",
        "Ecchi",
        "Fantasy",
        "Horror",
        "Mahou Shoujo",
        "Mecha",
        "Music",
        "Mystery",
        "Psychological",
        "Romance",
        "Sci-Fi",
        "Slice Of Life",
        "Sports",
        "Supernatural",
        "Thriller",
        "Anti-Hero",
        "Ensemble Cast",
        "Female Protagonist",
        "Male Protagonist",
        "Office Lady",
        "Primarily Adult Cast",
        "Primarily Child Cast",
        "Primarily Female Cast",
        "Primarily Male Cast",
        "Villainess",
        "Age Regression",
        "Agender",
        "Aliens",
        "Amnesia",
        "Artificial Intelligence",
        "Asexual",
        "Butler",
        "Centaur",
        "Chimera",
        "Chuunibyou",
        "Cosplay",
        "Crossdressing",
        "Delinquents",
        "Demons",
        "Detective",
        "Dinosaurs",
        "Dissociative Identities",
        "Dragons",
        "Dullahan",
        "Elf",
        "Ghost",
        "Goblin",
        "Gods",
        "Gyaru",
        "Hikikomori",
        "Idol",
        "Kemonomimi",
        "Kuudere",
        "Maids",
        "Mermaid",
        "Monster Girl",
        "Nekomimi",
        "Ninja",
        "Nudity",
        "Nun",
        "Oiran",
        "Ojou-Sama",
        "Pirates",
        "Robots",
        "Samurai",
        "Shrine Maiden",
        "Skeleton",
        "Succubus",
        "Tanned Skin",
        "Teacher",
        "Tsundere",
        "Twins",
        "Vampire",
        "Vikings",
        "Werewolf",
        "Witch",
        "Yandere",
        "Zombie",
        "Josei",
        "Kids",
        "Seinen",
        "Shoujo",
        "Shounen",
        "Bar",
        "Circus",
        "College",
        "Dungeon",
        "Foreign",
        "Language Barrier",
        "Outdoor",
        "Rural",
        "School",
        "School Club",
        "Urban",
        "Work",
        "Achronological Order",
        "Anachronism",
        "Dystopian",
        "Historical",
        "Time Skip",
        "Afterlife",
        "Alternate Universe",
        "Augmented Reality",
        "Post-Apocalyptic",
        "Space",
        "Urban Fantasy",
        "Virtual World",
        "4-Koma",
        "Achromatic",
        "Advertisement",
        "Anthology",
        "CGI",
        "Episodic",
        "Flash",
        "Full CGI",
        "Full Color",
        "No Dialogue",
        "POV",
        "Puppetry",
        "Rotoscoping",
        "Stop Motion",
        "Archery",
        "Battle Royale",
        "Espionage",
        "Fugitive",
        "Guns",
        "Martial Arts",
        "Swordplay",
        "Acting",
        "Calligraphy",
        "Classic Literature",
        "Drawing",
        "Fashion",
        "Food",
        "Photography",
        "Rakugo",
        "Writing",
        "Band",
        "Dancing",
        "Musical",
        "Parody",
        "Satire",
        "Slapstick",
        "Surreal Comedy",
        "Bullying",
        "Coming Of Age",
        "Conspiracy",
        "Rehabilitation",
        "Revenge",
        "Tragedy",
        "Body Swapping",
        "Cultivation",
        "Fairy Tale",
        "Henshin",
        "Isekai",
        "Kaiju",
        "Magic",
        "Mythology",
        "Shapeshifting",
        "Steampunk",
        "Super Power",
        "Superhero",
        "Wuxia",
        "Youkai",
        "Video Games",
        "Card Battle",
        "Go",
        "Karuta",
        "Mahjong",
        "Poker",
        "Shogi",
        "Airsoft",
        "American Football",
        "Athletics",
        "Badminton",
        "Baseball",
        "Basketball",
        "Boxing",
        "Cheerleading",
        "Cycling",
        "Fishing",
        "Fitness",
        "Football",
        "Golf",
        "Ice Skating",
        "Lacrosse",
        "Rugby",
        "Scuba Diving",
        "Skateboarding",
        "Surfing",
        "Swimming",
        "Table Tennis",
        "Tennis",
        "Volleyball",
        "Wrestling",
        "Animals",
        "Astronomy",
        "Autobiographical",
        "Biographical",
        "Body Horror",
        "Cannibalism",
        "Chibi",
        "Cosmic Horror",
        "Crime",
        "Crossover",
        "Death Game",
        "Denpa",
        "Drugs",
        "Economics",
        "Educational",
        "Environmental",
        "Ero Guro",
        "Gambling",
        "Gender Bending",
        "Gore",
        "LGBTQ+ Themes",
        "Lost Civilization",
        "Medicine",
        "Memory Manipulation",
        "Meta",
        "Noir",
        "Otaku Culture",
        "Pandemic",
        "Philosophy",
        "Politics",
        "Reincarnation",
        "Slavery",
        "Software Development",
        "Survival",
        "Terrorism",
        "War",
        "Assassins",
        "Cult",
        "Firefighters",
        "Gangs",
        "Mafia",
        "Military",
        "Police",
        "Triads",
        "Yakuza",
        "Aviation",
        "Cars",
        "Mopeds",
        "Motorcycles",
        "Ships",
        "Tanks",
        "Trains",
        "Age Gap",
        "Bisexual",
        "Boys' Love",
        "Harem",
        "Love Triangle",
        "Reverse Harem",
        "Teens' Love",
        "Yuri",
        "Cyberpunk",
        "Space Opera",
        "Time Manipulation",
        "Tokusatsu",
        "Real Robot",
        "Super Robot",
        "Cute Girls Doing Cute Things",
        "Family Life",
        "Iyashikei",
      ]
    },
  ],
};
