export default {
  cart: [],
  anime: [
    {
      anilist_id: 21,
      mal_id: 21,
      format: 0,
      status: 1,
      titles: {
        en: "One Piece",
        jp: "ワンピース",
        it: "One Piece",
      },
      descriptions: {
        en: "",
        it: "Monkey D. Luffy (Nel doppiaggio italiano, Rubber) è un pirata diciassettenne che da bambino ha mangiato il frutto del diavolo Gom Gom che gli ha permesso di diventare un uomo gomma perdendo però la facoltà di nuotare. Il suo sogno è quello di diventare il Re dei pirati trovando il leggendario One Piece, tesoro nascosto da Gol D. Roger, il vecchio Re dei pirati. Per riuscire nell'impresa Rufy dovrà formare la sua ciurma formata da amici e abili combattenti del quali il pirata potrà fidarsi ciecamente. Nasce così la Ciurma di Cappello di Paglia, legata dall'indissolubile legame dell'amicizia.",
      },
      start_date: "1999-10-20T00:00:00Z",
      end_date: "1970-01-01T00:00:00Z",
      season_period: 3,
      season_year: 1999,
      episodes_count: 1001,
      episode_duration: 24,
      cover_image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/nx21-tXMN3Y20PIL9.jpg",
      cover_color: "#e4a15d",
      banner_image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21-wf37VakJmZqs.jpg",
      genres: [
        "Action",
        "Adventure",
        "Comedy",
        "Drama",
        "Fantasy",
        "Pirates",
        "Ensemble Cast",
        "Shounen",
        "Super Power",
        "Conspiracy",
        "Male Protagonist",
        "Ships",
        "Badminton",
        "Airsoft",
        "Time Skip",
        "War",
        "Politics",
        "Lost Civilization",
        "Swordplay",
        "Henshin",
        "Real Robot",
        "Shapeshifting",
        "Animals",
        "Primarily Adult Cast",
        "Cult",
        "Super Robot",
        "Anachronism",
        "Skeleton",
        "Gender Bending",
        "Anti-Hero",
        "Espionage",
        "Ninja",
        "Cyborg",
        "Primarily Male Cast",
        "Guns",
        "Female Harem",
        "Kuudere",
        "Drugs",
        "Robots",
        "Mermaid",
        "Body Swapping",
        "Battle Royale",
        "Zombie",
        "Time Manipulation",
        "Dinosaurs",
        "Transgender",
        "Assassins",
        "Tanned Skin",
        "Adoption",
        "Asexual",
      ],
      score: 86,
      id: 11,
    },
    {
      anilist_id: 21,
      mal_id: 21,
      format: 0,
      status: 1,
      titles: {
        en: "One Piece",
        jp: "ワンピース",
        it: "One Piece",
      },
      descriptions: {
        en: "",
        it: "Monkey D. Luffy (Nel doppiaggio italiano, Rubber) è un pirata diciassettenne che da bambino ha mangiato il frutto del diavolo Gom Gom che gli ha permesso di diventare un uomo gomma perdendo però la facoltà di nuotare. Il suo sogno è quello di diventare il Re dei pirati trovando il leggendario One Piece, tesoro nascosto da Gol D. Roger, il vecchio Re dei pirati. Per riuscire nell'impresa Rufy dovrà formare la sua ciurma formata da amici e abili combattenti del quali il pirata potrà fidarsi ciecamente. Nasce così la Ciurma di Cappello di Paglia, legata dall'indissolubile legame dell'amicizia.",
      },
      start_date: "1999-10-20T00:00:00Z",
      end_date: "1970-01-01T00:00:00Z",
      season_period: 3,
      season_year: 1999,
      episodes_count: 1001,
      episode_duration: 24,
      cover_image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/nx21-tXMN3Y20PIL9.jpg",
      cover_color: "#e4a15d",
      banner_image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21-wf37VakJmZqs.jpg",
      genres: [
        "Action",
        "Adventure",
        "Comedy",
        "Drama",
        "Fantasy",
        "Pirates",
        "Ensemble Cast",
        "Shounen",
        "Super Power",
        "Conspiracy",
        "Male Protagonist",
        "Ships",
        "Badminton",
        "Airsoft",
        "Time Skip",
        "War",
        "Politics",
        "Lost Civilization",
        "Swordplay",
        "Henshin",
        "Real Robot",
        "Shapeshifting",
        "Animals",
        "Primarily Adult Cast",
        "Cult",
        "Super Robot",
        "Anachronism",
        "Skeleton",
        "Gender Bending",
        "Anti-Hero",
        "Espionage",
        "Ninja",
        "Cyborg",
        "Primarily Male Cast",
        "Guns",
        "Female Harem",
        "Kuudere",
        "Drugs",
        "Robots",
        "Mermaid",
        "Body Swapping",
        "Battle Royale",
        "Zombie",
        "Time Manipulation",
        "Dinosaurs",
        "Transgender",
        "Assassins",
        "Tanned Skin",
        "Adoption",
        "Asexual",
      ],
      score: 86,
      id: 11,
    },
    {
      anilist_id: 21,
      mal_id: 21,
      format: 0,
      status: 1,
      titles: {
        en: "One Piece",
        jp: "ワンピース",
        it: "One Piece",
      },
      descriptions: {
        en: "",
        it: "Monkey D. Luffy (Nel doppiaggio italiano, Rubber) è un pirata diciassettenne che da bambino ha mangiato il frutto del diavolo Gom Gom che gli ha permesso di diventare un uomo gomma perdendo però la facoltà di nuotare. Il suo sogno è quello di diventare il Re dei pirati trovando il leggendario One Piece, tesoro nascosto da Gol D. Roger, il vecchio Re dei pirati. Per riuscire nell'impresa Rufy dovrà formare la sua ciurma formata da amici e abili combattenti del quali il pirata potrà fidarsi ciecamente. Nasce così la Ciurma di Cappello di Paglia, legata dall'indissolubile legame dell'amicizia.",
      },
      start_date: "1999-10-20T00:00:00Z",
      end_date: "1970-01-01T00:00:00Z",
      season_period: 3,
      season_year: 1999,
      episodes_count: 1001,
      episode_duration: 24,
      cover_image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/nx21-tXMN3Y20PIL9.jpg",
      cover_color: "#e4a15d",
      banner_image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21-wf37VakJmZqs.jpg",
      genres: [
        "Action",
        "Adventure",
        "Comedy",
        "Drama",
        "Fantasy",
        "Pirates",
        "Ensemble Cast",
        "Shounen",
        "Super Power",
        "Conspiracy",
        "Male Protagonist",
        "Ships",
        "Badminton",
        "Airsoft",
        "Time Skip",
        "War",
        "Politics",
        "Lost Civilization",
        "Swordplay",
        "Henshin",
        "Real Robot",
        "Shapeshifting",
        "Animals",
        "Primarily Adult Cast",
        "Cult",
        "Super Robot",
        "Anachronism",
        "Skeleton",
        "Gender Bending",
        "Anti-Hero",
        "Espionage",
        "Ninja",
        "Cyborg",
        "Primarily Male Cast",
        "Guns",
        "Female Harem",
        "Kuudere",
        "Drugs",
        "Robots",
        "Mermaid",
        "Body Swapping",
        "Battle Royale",
        "Zombie",
        "Time Manipulation",
        "Dinosaurs",
        "Transgender",
        "Assassins",
        "Tanned Skin",
        "Adoption",
        "Asexual",
      ],
      score: 86,
      id: 11,
    },
    {
      anilist_id: 21,
      mal_id: 21,
      format: 0,
      status: 1,
      titles: {
        en: "One Piece",
        jp: "ワンピース",
        it: "One Piece",
      },
      descriptions: {
        en: "",
        it: "Monkey D. Luffy (Nel doppiaggio italiano, Rubber) è un pirata diciassettenne che da bambino ha mangiato il frutto del diavolo Gom Gom che gli ha permesso di diventare un uomo gomma perdendo però la facoltà di nuotare. Il suo sogno è quello di diventare il Re dei pirati trovando il leggendario One Piece, tesoro nascosto da Gol D. Roger, il vecchio Re dei pirati. Per riuscire nell'impresa Rufy dovrà formare la sua ciurma formata da amici e abili combattenti del quali il pirata potrà fidarsi ciecamente. Nasce così la Ciurma di Cappello di Paglia, legata dall'indissolubile legame dell'amicizia.",
      },
      start_date: "1999-10-20T00:00:00Z",
      end_date: "1970-01-01T00:00:00Z",
      season_period: 3,
      season_year: 1999,
      episodes_count: 1001,
      episode_duration: 24,
      cover_image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/nx21-tXMN3Y20PIL9.jpg",
      cover_color: "#e4a15d",
      banner_image:
        "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21-wf37VakJmZqs.jpg",
      genres: [
        "Action",
        "Adventure",
        "Comedy",
        "Drama",
        "Fantasy",
        "Pirates",
        "Ensemble Cast",
        "Shounen",
        "Super Power",
        "Conspiracy",
        "Male Protagonist",
        "Ships",
        "Badminton",
        "Airsoft",
        "Time Skip",
        "War",
        "Politics",
        "Lost Civilization",
        "Swordplay",
        "Henshin",
        "Real Robot",
        "Shapeshifting",
        "Animals",
        "Primarily Adult Cast",
        "Cult",
        "Super Robot",
        "Anachronism",
        "Skeleton",
        "Gender Bending",
        "Anti-Hero",
        "Espionage",
        "Ninja",
        "Cyborg",
        "Primarily Male Cast",
        "Guns",
        "Female Harem",
        "Kuudere",
        "Drugs",
        "Robots",
        "Mermaid",
        "Body Swapping",
        "Battle Royale",
        "Zombie",
        "Time Manipulation",
        "Dinosaurs",
        "Transgender",
        "Assassins",
        "Tanned Skin",
        "Adoption",
        "Asexual",
      ],
      score: 86,
      id: 11,
    },
  ],
};
